name: Script

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
   
    steps:
      - name: checkout Repository
        uses: actions/checkout@v2

      - name: Execute script on server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run:
          chmod 600 $HOME/.ssh/id_rsa
          ssh -0 StrictHostKeyChecking=no -i $HOME/ .ssh/id_rsa $SERVER_USER@$SERVER_HOST 'bash -s' < /tmp/test/script.sh
